### ISSUE TITLE
TexturePacker implementation fails without sprites directory

### ISSUE THREAD

**Issue by hammackj** [RoaringCatGames/libgdx-ashley-box2d-example#1]
$ ./gradlew texture-packer:run
Configuration on demand is an incubating feature.
:texture-packer:compileJava UP-TO-DATE
:texture-packer:processResources UP-TO-DATE
:texture-packer:classes UP-TO-DATE
:texture-packer:run
animations
puffin/puffin (alias of puffin/puffin)
puffin/puffin (alias of puffin/puffin)
puffin/puffin (alias of puffin/puffin)
puffin/puffin (alias of puffin/puffin)
puffin/puffin (alias of puffin/puffin)
puffin/puffin (alias of puffin/puffin)
puffin/puffin (alias of puffin/puffin)
Packing....
Packing....
Packing....
Packing....
Writing 2048x2048: ../android/assets/animations/animations.png
Writing 2048x2048: ../android/assets/animations/animations2.png
Writing 2048x2048: ../android/assets/animations/animations3.png
Writing 2048x2048: ../android/assets/animations/animations4.png
Exception in thread "main" java.lang.RuntimeException: Error packing images.
    at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:635)
    at GameTexturePacker.main(GameTexturePacker.java:39)
Caused by: java.lang.IllegalArgumentException: Input file does not exist: /Users/hammackj/Projects/opensource/libgdx-ashley-box2d-example/texture-packer/sprites
    at com.badlogic.gdx.tools.FileProcessor.process(FileProcessor.java:117)
    at com.badlogic.gdx.tools.texturepacker.TexturePackerFileProcessor.process(TexturePackerFileProcessor.java:70)
    at com.badlogic.gdx.tools.texturepacker.TexturePacker.process(TexturePacker.java:633)
    ... 1 more
:texture-packer:run FAILED

**Comment by Barryrowe** [comment]
Thanks for the report.

You should be able to pull the latest changes to get past this. I had inadvertently pointed to 2 non-existent  directories under TexturePacker in the texture-packer/src/GameTexturePacker class.

Resolved with this commit: 381a5f604d4e8007b39dcd1c59481f3cd1db1482
